package com.kakuhanashi.common.model;

import com.kakuhanashi.common.model.base.BaseBootuser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Bootuser extends BaseBootuser<Bootuser> {
	
}
