package com.kakuhanashi.common.model;

import com.jfinal.plugin.activerecord.Db;
import com.jfinal.plugin.activerecord.Record;
import com.kakuhanashi.common.model.base.BaseBootuser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Bootuser extends BaseBootuser<Bootuser> {
	
	public Record get(){
		String sql = "SELECT * FROM `bootuser` WHERE id >= (SELECT floor(RAND() * (SELECT MAX(id) FROM `bootuser`)))  ORDER BY id LIMIT 1;";
		return	Db.findFirst(sql);
		 
		
		
	}
}
