package com.kakuhanashi.common.model;

import com.kakuhanashi.common.model.base.BaseCodeMsg;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CodeMsg extends BaseCodeMsg<CodeMsg> {
	
}
