package com.kakuhanashi.common.model;

import com.kakuhanashi.common.model.base.BaseWords;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Words extends BaseWords<Words> {
	
}
