package com.kakuhanashi.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseCodeMsg<M extends BaseCodeMsg<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setCode(java.lang.String code) {
		set("code", code);
		return (M)this;
	}
	
	public java.lang.String getCode() {
		return getStr("code");
	}

	public M setField(java.lang.String field) {
		set("field", field);
		return (M)this;
	}
	
	public java.lang.String getField() {
		return getStr("field");
	}

	public M setMsg(java.lang.String msg) {
		set("msg", msg);
		return (M)this;
	}
	
	public java.lang.String getMsg() {
		return getStr("msg");
	}

	public M setRegexValue(java.lang.String regexValue) {
		set("regex_value", regexValue);
		return (M)this;
	}
	
	public java.lang.String getRegexValue() {
		return getStr("regex_value");
	}

	public M setRemark(java.lang.String remark) {
		set("remark", remark);
		return (M)this;
	}
	
	public java.lang.String getRemark() {
		return getStr("remark");
	}

}
